version: '2'

# for raspberry docker

services:
  web:
    build: .
    restart: always
    command: ./main_linux_arm
    ports:
      - 8080:8080
    volumes:
      - .:/go
      - ~/Downloads/meituri:/go/data